In [1]:
# Copyright (c) 2021 Delbert Yip
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

import numpy as np 
import pandas as pd 

In [2]:
data = [
    [0., 1., 2., 3.,],
    [0., 1., 2., 3.,],
    [0., 1., 2., 3.,],
    [0., 1., 2., 3.,]
]

In [9]:
data = np.array(data)
data[2]

array([0., 1., 2., 3.])

In [4]:
A = np.cumsum(data, 0)
A

array([[ 0.,  1.,  2.,  3.],
       [ 0.,  2.,  4.,  6.],
       [ 0.,  3.,  6.,  9.],
       [ 0.,  4.,  8., 12.]])

In [5]:
B = A[1::2] 
B

array([[ 0.,  2.,  4.,  6.],
       [ 0.,  4.,  8., 12.]])

In [6]:
C = B / float(2)
C

array([[0., 1., 2., 3.],
       [0., 2., 4., 6.]])

In [7]:
C[1:] = C[1:] - C[:-1]
C

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.]])