In [53]:
import regex as re  
import pandas as pd     
import os 

In [54]:
os.path.abspath("./src/GeneralProcessing/")

'c:\\Users\\delbe\\Downloads\\wut\\wut\\Post_grad\\UBC\\Research\\lab\\Github_repos\\EphysAnalysisTools\\src\\GeneralProcess\\src\\GeneralProcessing'

c:\Users\delbe\Downloads\wut\wut\Post_grad\UBC\Research\lab\Github_repos\EphysAnalysisTools\venv\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  """


TypeError: Panel() takes no arguments

In [2]:
data = [
    [0., 1., 2., 3.,],
    [0., 1., 2., 3.,],
    [0., 1., 2., 3.,],
    [0., 1., 2., 3.,]
]

In [9]:
data = np.array(data)
data[2]

array([0., 1., 2., 3.])

In [4]:
A = np.cumsum(data, 0)
A

array([[ 0.,  1.,  2.,  3.],
       [ 0.,  2.,  4.,  6.],
       [ 0.,  3.,  6.,  9.],
       [ 0.,  4.,  8., 12.]])

In [5]:
B = A[1::2] 
B

array([[ 0.,  2.,  4.,  6.],
       [ 0.,  4.,  8., 12.]])

In [6]:
C = B / float(2)
C

array([[0., 1., 2., 3.],
       [0., 2., 4., 6.]])

In [7]:
C[1:] = C[1:] - C[:-1]
C

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.]])