In [42]:
import regex as re  
import pandas as pd     

In [46]:
df = pd.DataFrame(index=range(5), columns=range(5))

In [47]:
def f(x):
    n = x.name 
    print(n)
    
df

0    1    2    3    4
0  NaN  NaN  NaN  NaN  NaN
1  NaN  NaN  NaN  NaN  NaN
2  NaN  NaN  NaN  NaN  NaN
3  NaN  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN  NaN

In [2]:
data = [
    [0., 1., 2., 3.,],
    [0., 1., 2., 3.,],
    [0., 1., 2., 3.,],
    [0., 1., 2., 3.,]
]

In [9]:
data = np.array(data)
data[2]

array([0., 1., 2., 3.])

In [4]:
A = np.cumsum(data, 0)
A

array([[ 0.,  1.,  2.,  3.],
       [ 0.,  2.,  4.,  6.],
       [ 0.,  3.,  6.,  9.],
       [ 0.,  4.,  8., 12.]])

In [5]:
B = A[1::2] 
B

array([[ 0.,  2.,  4.,  6.],
       [ 0.,  4.,  8., 12.]])

In [6]:
C = B / float(2)
C

array([[0., 1., 2., 3.],
       [0., 2., 4., 6.]])

In [7]:
C[1:] = C[1:] - C[:-1]
C

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.]])