In [15]:
from functools import singledispatch
import numpy as np 

@singledispatch
def mul(lst: list, x: float) -> list:
    return [x*y for y in lst]

@mul.register
def mul_pow(lst: tuple, x: float, pow: float, rev=True) -> list:
    
    X = [(x*y)**pow for y in lst]
    if rev: 
        X.reverse()
    
    return X

a = [3, 4, 6, 8]
mul((3, 4, 6, 8), 2, 1, rev=False)

[6, 8, 12, 16]

In [102]:
x = np.array(x)
x2 = np.full((4, 4), list(range(4)), dtype=float)

a = (2, 3)
b = [1, 2, 3, 4]
c = [2, 3, 4, 5]
list(zip(*[b, c]))

x2 [0] = 0

In [ ]:
# Copyright (c) 2021 Delbert Yip
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT



In [2]:
data = [
    [0., 1., 2., 3.,],
    [0., 1., 2., 3.,],
    [0., 1., 2., 3.,],
    [0., 1., 2., 3.,]
]

In [9]:
data = np.array(data)
data[2]

array([0., 1., 2., 3.])

In [4]:
A = np.cumsum(data, 0)
A

array([[ 0.,  1.,  2.,  3.],
       [ 0.,  2.,  4.,  6.],
       [ 0.,  3.,  6.,  9.],
       [ 0.,  4.,  8., 12.]])

In [5]:
B = A[1::2] 
B

array([[ 0.,  2.,  4.,  6.],
       [ 0.,  4.,  8., 12.]])

In [6]:
C = B / float(2)
C

array([[0., 1., 2., 3.],
       [0., 2., 4., 6.]])

In [7]:
C[1:] = C[1:] - C[:-1]
C

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.]])